import {
  Palette,
  BarChart3,
  Code2,
  FileSpreadsheet,
  Database,
  Table2,
  FileCode2,
  Atom,
  Terminal,
  Server,
  GitBranch,
  Mail,
  Phone,
  MapPin,
  Send,
  Download,
  ExternalLink,
  Briefcase,
  GraduationCap,
  Award,
  Users,
  FolderGit2,
  Layers,
  PenTool,
  LineChart,
  Rocket,
  Sparkles,
  Image as ImageIcon,
  BadgeCheck,
  Building2,
  FlaskConical,
} from "lucide-react";
import { FaDribbble, FaGithub, FaInstagram, FaLinkedin, FaXTwitter } from "react-icons/fa6";

// lucide-react no longer ships brand/logo icons, so brand marks (GitHub, LinkedIn,
// Twitter/X, Dribbble, Instagram) are sourced from react-icons instead.
export const iconMap = {
  Palette,
  BarChart3,
  Code2,
  FileSpreadsheet,
  Database,
  Table2,
  FileCode2,
  Atom,
  Terminal,
  Server,
  GitBranch,
  Mail,
  Phone,
  MapPin,
  Send,
  Download,
  ExternalLink,
  Briefcase,
  GraduationCap,
  Award,
  Users,
  FolderGit2,
  Layers,
  PenTool,
  LineChart,
  Rocket,
  Sparkles,
  Image: ImageIcon,
  BadgeCheck,
  Building2,
  FlaskConical,
  Github: FaGithub,
  Linkedin: FaLinkedin,
  Twitter: FaXTwitter,
  Instagram: FaInstagram,
  Dribbble: FaDribbble,
};

export function getIcon(name) {
  return iconMap[name] ?? Sparkles;
}
