import {
  Palette,
  BarChart3,
  Code2,
  FileSpreadsheet,
  Database,
  Table2,
  FileCode2,
  Atom,
  Terminal,
  Server,
  GitBranch,
  Mail,
  Phone,
  MapPin,
  Send,
  Download,
  ExternalLink,
  Briefcase,
  GraduationCap,
  Award,
  Users,
  FolderGit2,
  Layers,
  PenTool,
  LineChart,
  Rocket,
  Sparkles,
  Image as ImageIcon,
  BadgeCheck,
  Building2,
  FlaskConical,
  Microscope,
  BrainCircuit,
  HeartPulse,
  Stethoscope,
  MessageSquare,
  MessagesSquare,
  Globe,
  BookOpen,
  TestTube,
  Droplet,
  Bug,
  ShieldCheck,
  ClipboardCheck,
  Monitor,
  FileText,
  Search,
  Bot,
  Lightbulb,
} from "lucide-react";
import { FaGithub, FaInstagram, FaLinkedin, FaTiktok, FaWhatsapp } from "react-icons/fa6";

// lucide-react no longer ships brand/logo icons, so brand marks (GitHub, LinkedIn,
// TikTok, Instagram, WhatsApp) are sourced from react-icons instead.
export const iconMap = {
  Palette,
  BarChart3,
  Code2,
  FileSpreadsheet,
  Database,
  Table2,
  FileCode2,
  Atom,
  Terminal,
  Server,
  GitBranch,
  Mail,
  Phone,
  MapPin,
  Send,
  Download,
  ExternalLink,
  Briefcase,
  GraduationCap,
  Award,
  Users,
  FolderGit2,
  Layers,
  PenTool,
  LineChart,
  Rocket,
  Sparkles,
  Image: ImageIcon,
  BadgeCheck,
  Building2,
  FlaskConical,
  Microscope,
  BrainCircuit,
  HeartPulse,
  Stethoscope,
  MessageSquare,
  MessagesSquare,
  Globe,
  BookOpen,
  TestTube,
  Droplet,
  Bug,
  ShieldCheck,
  ClipboardCheck,
  Monitor,
  FileText,
  Search,
  Bot,
  Lightbulb,
  Github: FaGithub,
  Linkedin: FaLinkedin,
  Tiktok: FaTiktok,
  Instagram: FaInstagram,
  Whatsapp: FaWhatsapp,
};

export function getIcon(name) {
  return iconMap[name] ?? Sparkles;
}
